### ISSUE TITLE
How to get rules without creating an experiment?

### ISSUE THREAD

**Issue by suquark** [sigopt/sigopt-python#125]
It is quite important for me to get the rules before creating an experiment. It is not possible now because the rules endpoint needs the client id which is created by the experiment. So now I have to create fake experiments first and then update it. It is not very convenient.

```python
       self.connection = sigopt.Connection(client_token=client_token)
        # TODO: We cannot get rules before initializing an experiment, and experiments require parameters.
        # So we have to initialize an experiment with a fake experiment setting.
        self.experiment = self.connection.experiments().create(
            name=self.experiment_name,
            parameters=[{'name': '_fake', 'bounds': {'min': 0, 'max': 1}, 'type': 'double', 'default_value': 0.5}],
        )

        rules = self.connection.clients(self.experiment.client).plan().fetch().rules
        self._max_categorical_breadth = rules.max_categorical_breadth
        self._observation_budget_limit = rules.max_observations
```

**Comment by pfhayes** [comment]
Thanks for the feedback! Your client ID does not change and is fixed for your account. You can find it on this page: https://app.sigopt.com/tokens/info

If you use that value, you will always get the plan rules for your team (known as client in the API) and you do not need to create a fake experiment. Does that resolve your issue?

**Comment by mitar** [comment]
Hm, is there an API to get client ID? So that the user just has to provide the token?

**Comment by pfhayes** [comment]
@mitar no, there isn't one that's readily available. at this time you have to provide the client ID and the token together

what is your use case for this? would help if i could understand a bit better so we can prioritize this request

**Comment by mitar** [comment]
Oh, it is just so that users have one less thing to provide or make wrong. One less argument to the command line. If we could do this automatically, then we can. So we just have a workaround for now above.

**Comment by mitar** [comment]
The question is why do you even need client id at all in any of your endpoints and why not just use access token.

**Comment by pfhayes** [comment]
thanks @mitar ! that's very helpful and i appreciate the context. one of the challenges is making sure that `sigopt-python` works well for users who are members of multiple clients. we'll think a bit more about this and let you know if we make any changes that will make this workflow easier!

**Comment by mitar** [comment]
So in our context we are trying to provide SigOpt as an integration for our users. So less things they have configure (or copy-paste) better it is.

**Comment by tjs-intel** [comment]
closing because this issue is stale
