### ISSUE TITLE
How to access the plan with the development token?

### ISSUE THREAD

**Issue by suquark** [sigopt/sigopt-python#126]
Try to access the plan will raise `sigopt.exception.ApiException: ApiException (403): Development tokens cannot access this endpoint.`

However, accessing plans is important for testing because I can know if our project works well under the given plan constraints.

**Comment by mitar** [comment]
I would suggest that development plan output returns that all features are enabled.

**Comment by pfhayes** [comment]
Thanks for this feedback! We will investigate a solution for this on our end

**Comment by pfhayes** [comment]
This endpoint is now available to development tokens! Please let us know if this solves your issue
