### ISSUE TITLE
sigopt run on Windows

### ISSUE THREAD

**Issue by ashwinvaidya17** [sigopt/sigopt-python#189]
Hi,

I am using Windows 10.
sigopt version: 7.4.0

When I use ```sigopt run file.py```, I get ```TypeError: environment can only contain strings```.

The solution I found was to change line 84 in **config.py**
```return {self.CONTEXT_ENVIRONMENT_KEY: base64.b64encode(json.dumps(context).encode()).decode()}```
The ```.decode()``` converts byte to string.

Might be useful to someone using Windows 10.

**Comment by tjs-intel** [comment]
This should be resolved
