### ISSUE TITLE
APIConnectionError while creating experiment in Spark (Scala)

### ISSUE THREAD

**Issue by sidharth-iitkgp** [sigopt/sigopt-python#344]
I want to set API different than the default one. Currently I am using - 

```
Sigopt.clientToken = "<YOUR_CLIENT_TOKEN>"
Sigopt.setApiBase("https://YOUR_PROXY_URL")
```

But while creating the experiment I am getting the following error - 

![image](https://user-images.githubusercontent.com/41946423/156778737-747f5b94-512a-443b-be59-13bf64eeee2c.png)

In python we can do `conn.set_verify_ssl_certs(False)` and SLL certificate verification check is skipped. I guess I am looking for something similar in Scala Spark or Java.

**Comment by tjs-intel** [comment]
Apologies for the delayed response. The SigOpt Java client would be the correct place to report this issue: https://github.com/sigopt/sigopt-java
