### ISSUE TITLE
AttributeError python_2_unicode_compatible

### ISSUE THREAD

**Issue by cmishra** [sigopt/sigopt-python#47]
I am receiving the following error upon trying to import sigopt.interface on Python 3.4.3 using ubuntu 14.04. I have the problem with the terminal and Pycharm.

> Traceback (most recent call last):
>   File "/dos/Dropbox/College/4_Fourth_Year/STAT 5559/market predictions/run_model.py", line 2, in <module>
>     import numpy as np, sigopt.interface
>   File "/usr/local/lib/python3.4/dist-packages/sigopt/interface.py", line 14, in <module>
>     from .requestor import Requestor, DEFAULT_API_URL
>   File "/usr/local/lib/python3.4/dist-packages/sigopt/requestor.py", line 3, in <module>
>     from .exception import ApiException, ConnectionException
>   File "/usr/local/lib/python3.4/dist-packages/sigopt/exception.py", line 9, in <module>
>     @six.python_2_unicode_compatible
> AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

Any idea what the issue may be?

Thanks!

**Comment by pfhayes** [comment]
Thanks for the report Chetan! Can you try upgrading six and seeing if the problem persists?
Try running "pip install --upgrade six". Hopefully that fixes the issue!

-Patrick

    _____________________________

**Comment by cmishra** [comment]
Thanks for the quick reply!

I just did. It went from six-1.5.2 to six-1.9.0. Unfortunately, the problem is still occurring.

**Comment by sc932** [comment]
Hi Chetan,

That is still an old version of six. Can you try `pip install six==1.10.0`?

**Comment by pfhayes** [comment]
Are you using a python virtual environment? Can you also ascertain that the running code is using the correct version of six? Sometimes there can be conflicts between the version of six installed by the OS and the version you are running

If you do `import six; print(six.__version__)` before the `import sigopt.interface` it will inform you which version of `six` the running code is using - please ensure this is >= 1.9.0.

**Comment by cmishra** [comment]
Pip had installed six 1.10.0 (it's what it said it downloaded albeit it said 'installed six-1.9.0' after installation). Using `pip install six==1.10.0 -U` led to pip telling me the dependency was satisfied.

pfhayes's intuition was correct. I'm not running virtualenv (I'll fix that after my next clean install of ubuntu), so python was importing the system default for six (1.5.2) instead of 1.10.0 even though both were installed. 

Manually installing six via the instructions [here](http://stackoverflow.com/questions/28388976/installing-python-module-six?rq=1) did the trick. Thanks for your help!

**Comment by deepPython** [comment]
I am facing the same issue while running django server. I am not using virtual environment. Also, six package is on latest version in python. But still getting the error, What am I doing wrong?

pip show six

Name: six
Version: 1.10.0
Location: /usr/local/lib/python2.7/dist-packages
Requires

$python ~/django/mysite/manage.py runserver localhost
[1] 3913
$ AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

**Comment by kvegh** [comment]
> Hi Chetan,
> 
> That is still an old version of six. Can you try `pip install six==1.10.0`?

Thank you for this - solved my issue.
