### ISSUE TITLE
ApiResource has no attribute 'create'

### ISSUE THREAD

**Issue by cmishra** [sigopt/sigopt-python#48]
I'm trying to run the example on [this page](https://sigopt.com/docs/overview/python), but am receiving an error when trying to run the following command:
```
experiment = conn.experiments.create(
  name='New Experiment',
  parameters=[{ 'name': 'param1', 'type': 'double', 'bounds': { 'min': 0, 'max': 1.0 }}],
)
```

The error message is:

>   AttributeError: 'ApiResource' object has no attribute 'create'

Any idea what may be wrong? I'm on Ubuntu 14.04 Python 3.4.3.

**Comment by alexandraj777** [comment]
Hi Chetan,

Looks like we have a typo in this example. It should read:

experiment = conn.experiments().create(
  name='New Experiment',
  parameters=[{ 'name': 'param1', 'type': 'double', 'bounds': { 'min': 0, 'max': 1.0 }}],
)

With experiments() instead of experiments. Thanks for pointing this out, and we’ll fix this quickly!

Best,
Alexandra

**Comment by cmishra** [comment]
That resolved the issue, but now I'm receiving a different error message on the same code snipped:

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.4/dist-packages/sigopt/endpoint.py", line 22, in __call__
    raw_response = call(url, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sigopt/interface.py", line 111, in _post
    json=request_params,
  File "/usr/local/lib/python3.4/dist-packages/sigopt/requestor.py", line 16, in post
    return self._request('post', url=url, params=params, json=json, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/sigopt/requestor.py", line 33, in _request
    headers=headers,
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

**Comment by alexandraj777** [comment]
Hi Chetan,
You are most likely using an outdated version of the `requests` package. Looks like you may see this error in versions 2.4.2 and lower. We use `2.5.1`. Could you please try upgrading the package with `pip install --upgrade requests` and running the command again?
Thanks!

**Comment by cmishra** [comment]
I had to manually install again (#47), but it resolved the issue!  Thanks for your help Alexandra!

**Comment by cmishra** [comment]
Another documentation bug exists on that page I believe. The following command:

```
conn.experiments(experiment.id).observations().create(
  'suggestion': suggestion.id,
  'value': value,
)
```

doesn't work. The equivalent snipped [here](https://github.com/sigopt/sigopt-python/blob/master/examples/basic.py) does though.

**Comment by alexandraj777** [comment]
Yes you're right, this code snippet should read:
```
conn.experiments(experiment.id).observations().create(
  suggestion=suggestion.id,
  value=value,
)
```

**Comment by alexandraj777** [comment]
This will be fixed on the website soon!

**Comment by cmishra** [comment]
Just wanted to make sure you guys knew.

Thanks for your help!
