### ISSUE TITLE
Allow default API URL to be an environment variable

### ISSUE THREAD

**Issue by AbdealiJK** [sigopt/sigopt-python#92]
Currently the value of `DEFAULT_API_URL` is hardcoded. It would be great if we could set this using an environment variable similar to how `SIGOPT_API_TOKEN` is an env variable for the `client_token`.

Something like 'SIGOPT_DEFAULT_API_URL' ?

**Comment by pfhayes** [comment]
You can set the API url with the `set_api_url` method on the `Connection` object.

```
conn = sigopt.Connection('YOUR_CLIENT_TOKEN')
conn.set_api_url('https://YOUR_PROXY_URL')
```

Does that solve the issue?

**Comment by AbdealiJK** [comment]
I understand that, but would be better if I could do this at a system level
as compared to doing it in every code

**Comment by alexandraj777** [comment]
Hi @AbdealiJK, we're getting #93 out the door for you right now. Would you tell us a little more about your use case? We're curious to hear about which API url you're using.

**Comment by pfhayes** [comment]
Thanks for the report @AbdealiJK - this feature is now available in version 3.0.0 of the API client

**Comment by AbdealiJK** [comment]
Awesome! Thanks and really great speed

**Comment by sidharth-iitkgp** [comment]
How to set the same in Scala?

**Comment by sidharth-iitkgp** [comment]
@AbdealiJK did you get any error related to SSL certificate while using this fix?
I did the same and getting `ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')`

**Comment by AbdealiJK** [comment]
I have not had to use this library after 2019 as my work switched around that time.
So, I can't recall honestly - apologies

**Comment by dwanderson-intel** [comment]
Hey @sidharth-iitkgp - are you using either an on-prem version of SigOpt or running from a system that overwrites the standard CA certs (eg running inside a company VPN)? This error typically occurs when your client can't verify the certificate presented by the SigOpt server.

If either situation above applies, the usual solution is to talk to your company's IT department and have them provide you the appropriate CA certificate bundle. Then, in your code you can do:
 ```python
conn.set_verify_ssl_certs("path/to/ca-bundle")
```
or at the system level set an environment variable:
```bash
SIGOPT_API_VERIFY_SSL_CERTS=path/to/ca-bundle
```

Those are `sigopt-python`-client specific; I can take a look at the Scala client and see if there's anything extra we need there.
